trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)'
    arguments: '- o (BuildSourcesDirectory/dotnet)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: docker run -v $(Build.SourcesDirectory)/dotnet:/myapp/ --tty --rm veracode/pipeline-scan:cmd -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f '/myapp/NodeGoat.zip'